apis:
  - name: weather_berlin
    type: open_meteo
    url: "https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&current_weather=true"
    partition: False
  - name: weather_ny
    type: open_meteo
    url: "https://api.open-meteo.com/v1/forecast?latitude=40.71&longitude=-74.01&current_weather=true"
    partition: False
